# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170829_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
